### ISSUE TITLE
Silken Book

### ISSUE THREAD

**Issue by lumaa-dev** [V-Fast/BackroomsMod#11]
# Bug
It simply does nothing anymore

# How to reproduce
1. Get a Silken Book
2. Right click with the Silken Book
3. Nothing happens

# Expected behavior
Opens a randomly selected inscription

# Informations
- OS: Windows 10 & macOS
- Mod Version: potentially [Beta A0.1.0](https://modrinth.com/mod/backrooms/version/B-A0.1.0)
- Minecraft Version: 1.19.3+

**Comment by Clomclem** [comment]
Works now, I guess.
