### ISSUE TITLE
How to actually use the mod

### ISSUE THREAD

**Issue by Dashy22** [V-Fast/BackroomsMod#28]
So i downloaded the mod and made a world, what do i do?
Do i need to type a command or do something
This is not explained anywhere and I just want to play the backrooms.

**Comment by Dashy22** [comment]
Ma Fault
You gotta make your own portal sorry didn't read documentation.
You should probably put that somewhere or make a more obvious way in.

**Comment by lumaa-dev** [comment]
> You should probably put that somewhere or make a more obvious way in.

There's a whole banner for that
