### ISSUE TITLE
Backrooms Level 0 not generating rooms.

### ISSUE THREAD

**Issue by BabblingFishes** [V-Fast/BackroomsMod#7]
Entering Level 0 of the backrooms generates only the back-floor... No back-rooms...

Using:
- Minecraft 1.19.2 (singleplayer client)
- Fabric loader version 0.14.10-1.19.2
- fabric-api-0.64.0+1.19.2
- cloth-config-8.0.75-fabric
- thebackrooms-ALPHA-A0.0.4

Steps to reproduce:
- Open new creative world
- Build an iron block portal
- "Light" it with silk
- Enter the portal
- Witness an endless flat dimension of moist carpet and bedrock below that. No rooms.

Log file:
[2022-11-06-6.log](https://github.com/u-lumaa/BackroomsMod/files/9946924/2022-11-06-6.log)

Screenshot:
![image](https://user-images.githubusercontent.com/14933600/200197913-d466b82b-02ee-44b5-811a-fc5a59142af0.png)

**Comment by u-lumaa** [comment]
This feature, of generating randomized rooms, isn’t complete. As you can see [there](https://trello.com/c/oeXBwsgv) on our Trello Board.
The mod will no longer be in Alpha once this feature will be worked on, it will be in Beta, and once this feature is fully completed, it will no longer be in Alpha or Beta

We will keep this issue opened.

**Comment by BabblingFishes** [comment]
Ah! Apologies, I was under the impression from the screenshots that it was already functional.

**Comment by u-lumaa** [comment]
> I was under the impression from the screenshots that the generation was already functional.

This wasn’t our intention, we apologize for the misunderstanding!

**Comment by Clomclem** [comment]
Fixed in 0.2.0
